### ISSUE TITLE
Alter text from ‘antichronological’ to ‘by oldest first’

### ISSUE THREAD

**Issue by robertbrook** [ukparliament/Treaty#1]
Text which reads ‘antichronological’ should read ‘by oldest first’.

**Comment by robertbrook** [comment]
Debate ensues. By most recent laid date? Agreed on ‘reverse chronological’.

**Comment by matthieubosquet** [comment]
Place in the code: https://github.com/ukparliament/Treaty/blob/e8647ee5eaa8152376c81eb5c649c87fea67844b/UKParliament/Views/Treaty/Index.cshtml#L71

**Comment by robertbrook** [comment]
Done!
